name: lorawan
description: "LoRAWAN Network Optimizer Dashboard"

publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  mqtt_client: ^10.9.2
  connectivity_plus: ^6.1.4
  intl: ^0.20.2
  fl_chart: 1.0.0
  onnxruntime: ^1.4.1
  tflite_flutter: ^0.11.0
  timezone: ^0.10.1
  bitsdojo_window: ^0.1.6
dependency_overrides:
  fl_chart: 1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/